/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GamePage from "./GamePage/GamePage"
import GameStart from "./GameStart/GameStart"
import comfirmButton from "./comfirmButton"
import cancelButton from "./cancelButton"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("GamePage/GamePage.js",GamePage);
		reg("GameStart/GameStart.js",GameStart);
		reg("comfirmButton.js",comfirmButton);
		reg("cancelButton.js",cancelButton);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "GamePage.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
